server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        - id: catalogue-service
          uri: lb://catalogue-service
          predicates:
            - Path=/api/catalog/**
          filters:
            - StripPrefix=2
        - id: order-service-cart
          uri: lb://order-service
          predicates:
            - Path=/api/cart/**
          filters:
            - StripPrefix=1
        - id: order-service-order
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=1
        - id: admin-catalogue
          uri: lb://catalogue-service
          predicates:
            - Path=/api/admin/items/**
          filters:
            - StripPrefix=2
        - id: admin-orders
          uri: lb://order-service
          predicates:
            - Path=/api/admin/orders/**
          filters:
            - StripPrefix=2
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:4200"
              - "http://localhost:4201"
              - "http://localhost:4202"
              - "http://localhost:4203"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.web.cors: INFO
